const data = {
  products: [
    {
      _id: '1',
      name: 'Tea',
      category: 'Food',
      image: '/images/11 tea.jpg',
      price: 120,
      countInStock: 100,
      brand: 'Tata',
      rating: 5.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Noodles',
      category: 'Food',
      image: 'http://localhost:3000/images/17%20noodles.jpg',
      price: 32,
      countInStock: 20,
      brand: 'Maggi',
      rating: 4.0,
      numReviews: 20,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Salt',
      category: 'Food',
      image: '/images/3 salt.jpg',
      price: 30,
      countInStock: 1000,
      brand: 'Tata',
      rating: 4.8,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Soft Drink',
      category: 'Drink',
      image: '/images/15 softdrink.jpg',
      price: 100,
      countInStock: 15,
      brand: 'Coca Cola',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Mustard Oil',
      category: 'Food',
      image: '/images/5 mustard oil.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Fortune',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Choclate',
      category: 'Diary',
      image: '/images/20 chocolate.jpg',
      price: 20,
      countInStock: 0,
      brand: 'Peers',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;